dist: trusty
sudo: false
language: ruby

rvm:
  - 2.4.0
  - 2.3.4

branches:
  only:
    - master

env:
  global:
    - LOCAL_BUILDS="$HOME/local-builds"
    - BOTAN_INSTALL="${LOCAL_BUILDS}/botan-install"
    - LD_LIBRARY_PATH="${BOTAN_INSTALL}/lib"

cache:
  bundler: true
  directories:
    - "$BOTAN_INSTALL"

before_install:
  - gem install bundler -v 1.13.7
  - ./ci/install.sh

script: bundle exec rubocop && bundle exec rake
